services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    env_file:
      - ./backend/.env
    image: surf-backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    image: surf-frontend
    ports:
      - 80:80




