@hostname = http://localhost:4000

// request for /SurfSpot
GET {{hostname}}/surfSpot?userID=1

###

PUT {{hostname}}/surfSpot
Content-Type: application/json

{
    "spotID": 1,
    "name": "Sloppity Rockity",
    "latitude": 123.4, 
    "longitude": 69.42,
    "firstBuoyID": 7,
    "secondBuoyID": 242
}

###

DELETE {{hostname}}/surfSpot?spotID=18

###

POST {{hostname}}/surfSpot
Content-Type: application/json

{
    "userID": 1,
    "name": "Tizzle Tots",
    "latitude": 37.54,
    "longitude": 122.51,
    "firstBuoyID": null,
    "secondBuoyID": null
}

###

GET {{hostname}}/ideal?spotID=1

###

POST {{hostname}}/ideal
Content-Type: application/json

{
    "spotID": 3,
    "windDir": "nw",
    "swellDir": "sw",
    "size": "Head High",
    "period": "Short",
    "tideMax": 1.0,
    "tideMin": 2.5
}

###

PUT {{hostname}}/ideal
Content-Type: application/json

{
    "spotID": 1,
    "windDir": "nnw",
    "swellDir": "SW",
    "size": "Head High",
    "period": "Medium",
    "tideMax": 2.0,
    "tideMin": 5.0
}

###

GET {{hostname}}/Sessions?userID=1

###

POST {{hostname}}/Sessions
Content-Type: application/json

{
    "spotID": 2,
    "date": "2024-05-15",
    "windSpd": 11,
    "windDir": 322,
    "swellHgt": 3.2,
    "swellPer": 8,
    "swellDir": 310,
    "tide": 3.6,
    "swellAct": "slack",
    "tideDir": "decreasing",
    "description": "sucked"
}

###

DELETE {{hostname}}/Sessions?sessionID=2

###

// request for /request
GET http://localhost:5000/request?stationID=46026

###

// request for /request all
GET http://localhost:5000/request?stationID=all