@hostname = http://localhost:5000

// request for /SurfSpot
GET {{hostname}}/surfSpot?spotID=1

###

PUT {{hostname}}/surfSpot
Content-Type: application/json

{
    "spotID": 1,
    "name": "Sloppity Rockity",
    "latitude": 123.4, 
    "longitude": 69.42,
    "firstBuoyID": 7,
    "secondBuoyID": 242
}

###

DELETE {{hostname}}/surfSpot?spotID=18

###

POST {{hostname}}/surfSpot
Content-Type: application/json

{
    "userID": 1,
    "name": "Tizzle Tots",
    "latitude": 37.54,
    "longitude": 122.51,
    "firstBuoyID": null,
    "secondBuoyID": null
}

###


// request for /request
GET {{hostname}}/request?stationID=46237


