@hostname = http://localhost:5000

// request for /SurfSpot
GET {{hostname}}/surfSpot?spotID=1

###

PUT {{hostname}}/surfSpot
Content-Type: application/json

{
    "spotID": 1,
    "name": "Sloppity Rockity",
    "latitude": 123.4, 
    "longitude": 69.42,
    "firstBuoyID": 7,
    "secondBuoyID": 242
}

###

DELETE {{hostname}}/surfSpot?spotID=18

###

POST {{hostname}}/surfSpot
Content-Type: application/json

{
    "userID": 1,
    "name": "Tizzle Tots",
    "latitude": 37.54,
    "longitude": 122.51,
    "firstBuoyID": null,
    "secondBuoyID": null
}

###

GET {{hostname}}/ideal?spotID=1

###

POST {{hostname}}/ideal
Content-Type: application/json

{
    "spotID": 1,
    "windDir": "ssw",
    "swellDir": "nw",
    "size": "Double Overhead",
    "period": "long",
    "tideMax": 2.3,
    "tideMin": 4.2
}

###

PUT {{hostname}}/ideal
Content-Type: application/json

{
    "spotID": 1,
    "windDir": "nnw",
    "swellDir": "SW",
    "size": "Head High",
    "period": "Medium",
    "tideMax": 2.0,
    "tideMin": 5.0
}

###

// request for /request
GET {{hostname}}/request?stationID=46237


